### PR TITLE
344 pillboxes

### PR DESCRIPTION
**Pull request by NealHumphrey**
Adds the pillboxes. Here's a demo:
demo_pillboxes

@ptgott or @ostermanj a quick review would be helpful! I'll be merging by end of day today so it'll be ready for demos before I leave, but a post-merge review to check for bugs still welcome.

### CODE REVIEW

**Comment by ostermanj** [comment]
@NealHumphrey The demo's looking great. I'm back from my trip and hope to get back into the code soon. When are you leaving?

**Comment by NealHumphrey** [comment]
@ostermanj my flight is out of Dulles at 10am tomorrow, so will be wrapping up in the next hour or two. I'll probably do a bit on the planes tomorrow too, but by then I'll likely stay away from the #344 checklist and just do some Buildings page cleanup since that's still in a pretty raw state. 

I'm working on a few of the smaller items in #344 now, if you start anything before I sign off just ping me on Slack, otherwise I'll leave a note on #344 with where things stand - mostly by checking off the checkboxes of everything I've done. 

For the most part I think we won't need more API changes for now so should be all front end, which can be deployed to the live site with a simple merge to the master branch.

**Comment by ostermanj** [comment]
Cool. So if we commit improvements to dev before Tuesday we should then merge to master for the user testing?

**Comment by NealHumphrey** [comment]
Yep. I'll make sure you and @ptgott have permission to push to master - that way you can either a) do a pull request and have the other one approve it, or b) do the merge to master locally and push to master (i.e. to deploy on your own without the other person needing to approve). a) is preferred option for QA/transparency but b) in case it's needed.  I'm assuming your master is following the codefordc one without extraneous edits.

**Pull request merged**
