### PR TITLE
Issue 169 encoding param

### PR DESCRIPTION
**Pull request by speedyturkey**
This is my first PR so please be gentle - I believe I understand the DataReader classes and that this code will work. I did not think it necessary to implement a new __iter__ method on the DataReader class, but rather modified that method on HIReader.

Probably no need to keep the add_encoding_to_meta_json.py script but thought I'd share anyway.

I'm grateful for any feedback and happy to tweak further if necessary.

### CODE REVIEW

**Comment by speedyturkey** [comment]
Added the requested changes to make_draft_json. Do I understand correctly that when running make_draft_json on the full manifest, that it generates individual json files? Should that function generate a complete, unified json instead?

**Comment by NealHumphrey** [comment]
@speedyturkey heads up, when running this locally I realized there's some conflicting implentation of this. It's the confusing manifest vs. meta issue. Since manifest has rows on a per-file basis, we want to put the encoding definition there. Your DataReader class looks for the encoding param in the manifest_row class, but you actually put it in the table metadata. 

In the data reader, when you do manifest_row.get('encoding', 'latin-1'), the silent fallback default hides the fact that this param was never actually found. I realized this because I wanted to add logging anytime the fallback was used, since we want to avoid silent bugs when people don't correctly add a data source. 

I'll fix this in the current dev since I've already merged this PR. Just wanted to give you a heads up if you look at this code again later.

**Comment by NealHumphrey** [comment]
@speedyturkey fyi, here's the commit that resolves this: https://github.com/codefordc/housing-insights/commit/0006f5d456657012551242e1304b2ab14f846362

**Comment by speedyturkey** [comment]
Great catch, thanks for pointing out. I like your solution.

**Pull request merged**
