### PR TITLE
243 unique data id fix

### PR DESCRIPTION
**Pull request by jkwening**
Includes only the fix for resolving automatically adding 'unique_data_id' into the draft json file. #243 

This pull request only includes update to the make_draft_json.py.

### CODE REVIEW

**Comment by jkwening** [comment]
@NealHumphrey please postpone - it looks like it includes all my commits related to #194 and minor refactoring with the load data workflow. Unless you can cleanly do so, I will find a better way to only include the fix to make_draft_json.py. Sorry about all the additional changes...still getting used to git.

**Comment by NealHumphrey** [comment]
@jkwening I can pull the make_draft_json changes out on their own using --patch or manually. But I'd be happy to include all your refactor updates (looks like lots of line break and comment changes) as well as your DCHousingApiConn updates if they're ready. On a read through of the diff here on Github I didn't see anything amiss - how close is all this other stuff to being ready? 

a) If it's ready now I can pull and test locally
b) If there's something missing, let me know how close you are - if you'll get to it later today so that we can merge all the stuff in before Tuesday's session, I'll just hold off till then
c) If it'll be longer than that, I'll go ahead and --patch in the meta.json hotfix. 

Let me know!

**Comment by jkwening** [comment]
@NealHumphrey okay, looks like we're good to go now - it only includes the change to make_draft_json.py

**Comment by jkwening** [comment]
Haha ironically, I just wiped the branch and updated with only the make_draft_json module change via work laptop. Everything was ready and still available on my personal laptop at home, so I can push back later this evening or you can proceed with this hotfix and I can add the rest to DCHousingApiConn pull request. Let me know how you want to proceed?

**Comment by NealHumphrey** [comment]
@jkwening Great, I'll go ahead and merge this PR in then, and when the rest of the DCHousing stuff is done you can open a separate PR for that. It'd be great to get your documentation changes in before tomorrow though so that a) folks can have them and b) we (try to) avoid merge conflicts when other people edit the same files. Big refactors are always tricky and the faster they get done the less conflicting code people have time to write.

**Pull request merged**
