### PR TITLE
Merge pull request #1 from codefordc/dev

### PR DESCRIPTION
**Pull request by Janalyn**
DC Tech Meetup Code

### CODE REVIEW

**Comment by NealHumphrey** [comment]
@Janalyn I'm not sure what this pull request is for? Were you just trying to update your fork or did you intend for there to be something brought into the Code for DC fork?

**Comment by Janalyn** [comment]
I was trying to update my fork and hit it by accident. You can ignore that.

**Comment by Janalyn** [comment]
Added map tilt feature

**Comment by NealHumphrey** [comment]
@Janalyn Looks like this was reopened. On Tuesday you mentioned doing some work w/ the legend  - is this what you were talking about? Is this ready for review?

**Comment by Janalyn** [comment]
Hello,
I added a map tilt control above the legend. I was trying to make a new
pull request but I think I closed it by hitting the wrong submit button.
Let me know if you did not receive the files with the  map tilt. My github
skills still need a little work.

Best,
Janalyn

On May 4, 2017 2:08 PM, "Neal Humphrey" <notifications@github.com> wrote:

@Janalyn <https://github.com/Janalyn> Looks like this was reopened. On
Tuesday you mentioned doing some work w/ the legend - is this what you were
talking about? Is this ready for review?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codefordc/housing-insights/pull/228#issuecomment-299264984>,
or mute the thread

**Comment by Janalyn** [comment]
Will we have access to historical data? Should we put in a time slider?

**Comment by NealHumphrey** [comment]
@Janalyn Many of our data sources will have a time element, yes - so a time slider would be useful. We'll need to figure out how to structure the data appropriately to connect to the slider of course, though.

**Pull request closed without merging**
