### PR TITLE
Fixed db name to match secrets.json, switched wmata example with crim…

### PR DESCRIPTION
**Pull request by ajhalani**
…e as wmata example was broken

I wanted to get_api_data.py in a functioning state so folks can test with it if they want. I did add wmata key in secrets.json, this was the error I got with wmata_distcalc - 

```
$ python scripts/get_api_data.py 
  The unique_data_id 'wmata_dist' is not supported by the DCHousingApiConn
  The unique_data_id 'wmata_stops' is not supported by the DCHousingApiConn
  Connected to Housing Insights database
Starting new HTTPS connection (1): api.wmata.com
https://api.wmata.com:443 "GET /Rail.svc/json/jStations HTTP/1.1" 200 5997
  Processing project 0 of 360
  Starting processing rail stations for NL000001
Starting new HTTPS connection (1): api.mapbox.com
https://api.mapbox.com:443 "GET /directions/v5/mapbox/walking/-77.0221966,38.90811789;-77.028099,38.898303?access_token= HTTP/1.1" 401 39
The request for "wmata_distcalc" failed. Error: 'routes'
Traceback (most recent call last):
  File "scripts/get_api_data.py", line 71, in <module>
    get_multiple_api_sources(unique_data_ids,sample,output_type,db,debug)
  File "scripts/get_api_data.py", line 62, in get_multiple_api_sources
    raise e
  File "scripts/get_api_data.py", line 56, in get_multiple_api_sources
    api_method(unique_data_ids, sample, output_type, db=db)
  File "/home/ajhalani/work/housing-insights/python/housinginsights/sources/wmata_distcalc.py", line 43, in get_data
    self.get_dist(unique_data_ids=['wmata_dist'],sample=sample,output_type=output_type,db=db)
  File "/home/ajhalani/work/housing-insights/python/housinginsights/sources/wmata_distcalc.py", line 123, in get_dist
    self._find_rail_stations(self.railStations,project_details,radius,sample=sample)
  File "/home/ajhalani/work/housing-insights/python/housinginsights/sources/wmata_distcalc.py", line 269, in _find_rail_stations
    walkDist = self._get_walking_distance(lat, lon, str(station['Lat']), str(station['Lon']))
  File "/home/ajhalani/work/housing-insights/python/housinginsights/sources/wmata_distcalc.py", line 237, in _get_walking_distance
    return walkDistResponse.json()['routes'][0]['legs'][0]['distance']
KeyError: 'routes'

```

### CODE REVIEW

**Comment by ajhalani** [comment]
@jgordo04 - Jamie maybe you can help why the wmata code is giving error with get_api_data.py

**Comment by xee5ch** [comment]
No need for @jgordo04 to respond if she is busy. I consulted with @NealHumphrey who has been updated on the situation and intends to merge updated code and update the CSV files in the S3 bucket accordingly.  In the interim you have two options.

1) Manually edit the meta.json or manifest.csv file accordingly to match column headers as indicated in the error message. (Safest)

2) If you are using the dev branch (`git branch -v` should return a star like * next to dev or you are on a custom branch if you see * next to anything else) you can run the following commands. `git stash; git checkout HEAD~1 -- python/housing-insights/meta.json #### THIS WILL CAUSE PERMANENT DELETION IF YOU MISS EVERYTHING AFTER -- AND YOU SHOULD READ THIS` which will peel back just the meta.json file for the time being and leaving everything else. Again, Neal will resolve this soon.

**Comment by jgordo04** [comment]
Looks like @xee5ch figured this one out, but just want to note i think it would be `python/scripts/meta.json` in this statement `git stash; git checkout HEAD~1 -- python/housing-insights/meta.json` instead of `python/housing-insights/meta.json` (in case you were banging your head against the wall). Thanks @xee5ch for helping with that one!

**Comment by ajhalani** [comment]
Thank you guys!

**Pull request closed without merging**
